### ISSUE TITLE
feedstock is not building but staged-recipes is

### ISSUE THREAD

**Issue by klugem** [conda-forge/gradle-feedstock#3]
Gradle recipe is building in staged-recipes (https://github.com/conda-forge/staged-recipes/pull/9666) but not after conversion to feedstock.

I think there is a difference in the build steps between feedstock and staged-recipes causing that error...

 @conda-forge/staged-recipes : Any idea ?

**Comment by klugem** [comment]
Error message:
```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/home/conda/feedstock_root/build_artifacts/gradle_1569530617288/work/build.gradle.kts' line: 181

* What went wrong:
Failed to apply plugin [id 'gradlebuild.buildscan']
> Build scan custom link url cannot be null.

```

**Comment by klugem** [comment]
I also opened a issue at https://github.com/gradle/gradle/issues/10909

**Comment by klugem** [comment]
The **CI** environment variable caused the problem.

**Comment by jakirkham** [comment]
cc @conda-forge/core

**Comment by CJ-Wright** [comment]
Ah so the build itself had some CI env var hooks?

**Comment by klugem** [comment]
Yes.

**Comment by klugem** [comment]
The gradle code contains multiple lines similar to that one

> boolean isCiServer = System.getenv().containsKey("CI")

And if isCiServer is true, the buildscan plugin expects an link set via the env var BUILD_URL.

https://github.com/gradle/gradle/blob/27b3bfbb385558069bbea0fdf610cea6aea5639d/buildSrc/subprojects/profiling/src/main/kotlin/org/gradle/gradlebuild/profiling/buildscan/BuildScanPlugin.kt

**Comment by jakirkham** [comment]
Actually it's curious that the `CI` environment variable got passed through. Would have thought conda-build would clear this. Or is `CI` a passthrough environment variable?

**Comment by chrisburr** [comment]
`CI=azure` is used by the scripts from `conda-smithy` and I recently had to add it on `staged-recipes` to deal with a recent update.

**Comment by jakirkham** [comment]
Sure that's fine. What's surprising is that it is still set when conda-build runs. Normally it doesn't allow environment variables to seep into the build like this.
