### ISSUE TITLE
osx-arm64 support

### ISSUE THREAD

**Issue by jonmmease** [conda-forge/gradle-feedstock#61]
### Comment:

Hi! Thanks for managing the gradle feedstock. What would it take to get an osx-arm64 package published?

Edit: I just saw https://github.com/conda-forge/gradle-feedstock/pull/59, thanks for working on this @srilman!

**Comment by freundTech** [comment]
This is a java tool. Shouldn't this be built noarch anyways?

**Comment by freundTech** [comment]
Feedstock is now noarch and should work on osx-arm64. Closing.
